### ISSUE TITLE
Low Fidelity Prototype Sketches

### ISSUE THREAD

**Issue by JFMcAuley** [DECO3500-2022/Lost-At-Sea#1]
Hey Guys, 

Please can you add the low-fidelity prototype sketches you all did to the prototype file? Maybe a description or annotation might also be beneficial. Please can you do this by Wednesday (12/09/2022)?

Thanks,
James

**Comment by AdrianLSY** [comment]
I have the paper prototypes, I'll get it scanned and upload them

**Comment by JFMcAuley** [comment]
Done
